version: '3.2'
services:
  builder:
    build:
      context: ngic
      dockerfile: Dockerfile-builder
    image: ngiccorddemo/ngic-builder:$tag

  cp:
    build:
      context: ngic
      dockerfile: Dockerfile-cp
      args:
      - tag=$tag
    image: ngiccorddemo/ngic-cp:$tag
    volumes:
    - ./config:/opt/ngic/config
    networks:
      s11_net:
        aliases:
        - spgw.s11.ngic
      cpdp_net:
        aliases:
        - cp.cpdp.ngic

  dp:
    build:
      context: ngic
      dockerfile: Dockerfile-dp
      args:
      - tag=$tag
    image: ngiccorddemo/ngic-dp:$tag
    cap_add:
    - NET_ADMIN
    - IPC_LOCK
    volumes:
    - ./config:/opt/ngic/config
    networks:
      s1u_net:
        aliases:
        - spgw.s1u.ngic
      sgi_net:
        aliases:
        - spgw.sgi.ngic
      cpdp_net:
        aliases:
        - dp.cpdp.ngic

  traffic:
    build:
      context: dockerfiles
      dockerfile: Dockerfile-traffic
    image: ngiccorddemo/ngic-traffic
    cap_add:
    - NET_ADMIN
    volumes:
    - ./pcap:/opt/ngic/pcap
    networks:
      s11_net:
        aliases:
        - mme.s11.ngic
      s1u_net:
        aliases:
        - enb.s1u.ngic
      sgi_net:
        aliases:
        - app.sgi.ngic
    stdin_open: true
    tty: true

networks:
  s11_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "s11_net"
    ipam:
      driver: default
      config:
        - subnet: 1.1.1.0/24
  s1u_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "s1u_net"
    ipam:
      driver: default
      config:
        - subnet: 2.2.2.0/24
  sgi_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "sgi_net"
    ipam:
      driver: default
      config:
        - subnet: 3.3.3.0/24
  cpdp_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "cpdp_net"
    ipam:
      driver: default
      config:
        - subnet: 4.4.4.0/24
