FROM ngiccorddemo/ngic-builder as dp-builder

ENV NG_CORE /opt/ng-core
COPY . ${NG_CORE}
WORKDIR ${NG_CORE}

RUN make clean && make -j4 build-lib && make -j4 build-dp EXTRA_CFLAGS="-DSTATS -DOSTATS"

FROM ubuntu:16.04
RUN apt-get update && apt-get -y install \
    libzmq5 libstdc++6 libgcc1 \
    iputils-ping iproute2
RUN apt-get -y install tcpdump net-tools traceroute mtr dnsutils bind9-host hostname ethtool netcat
COPY --from=dp-builder /opt/ng-core/dp/build/ngic_dataplane /opt/ngic/bin/ngic_dataplane

# 20 CP/DP Comm
EXPOSE 20/UDP

#Mount the config folder here at runtime
VOLUME /opt/ngic/config

WORKDIR /opt/ngic/bin
CMD . /opt/ngic/config/dp_config.cfg && \
	ip link set dev $S1U_IFACE address $S1U_MAC && \
	ip link set dev $SGI_IFACE address $SGI_MAC && \
	./ngic_dataplane $EAL_ARGS -- $APP_ARGS
