ARG tag=latest
FROM ngiccorddemo/ngic-builder:${tag} as cp-builder

ENV NG_CORE /opt/ng-core
COPY . ${NG_CORE}
WORKDIR ${NG_CORE}

RUN make clean && make -j4 build-cp

FROM ubuntu:16.04
RUN apt-get update && apt-get -y install \
    libpcap0.8-dev libcurl4-openssl-dev \
    libjson0-dev \
    iputils-ping iproute2
RUN apt-get -y install tcpdump net-tools traceroute mtr dnsutils bind9-host hostname ethtool netcat
COPY --from=cp-builder /opt/ng-core/cp/build/ngic_controlplane /opt/ngic/bin/ngic_controlplane

# 2123 GTP-Control
EXPOSE 2123/UDP

# Mount the config folder here at runtime
VOLUME /opt/ngic/config

WORKDIR /opt/ngic/bin

# Step setting MAC addr is only required the demo
CMD . /opt/ngic/config/cp_config.cfg && ifconfig -a && \
    ./ngic_controlplane $EAL_ARGS -- $APP_ARGS
