FROM ubuntu:16.04
RUN apt-get update && apt-get -y install \
        tcpdump tcpreplay net-tools traceroute mtr dnsutils \
	bind9-host hostname ethtool iputils-ping iproute2

VOLUME /opt/ngic/pcap
WORKDIR /opt/ngic/pcap

CMD /bin/bash
