FROM ubuntu:16.04
RUN apt-get update && apt-get -y install python python-pip \
        tcpdump tcpreplay net-tools traceroute mtr dnsutils \
	bind9-host hostname ethtool iputils-ping iproute2 && \
    pip install https://github.com/secdev/scapy/archive/d45bd9.zip

VOLUME /opt/ngic/pcap
WORKDIR /opt/ngic/pcap

CMD /bin/bash
